### ISSUE TITLE
当不存在 Pair 时，提示用户去创建。

### ISSUE THREAD

**Issue by lychees** [carboclan/y3d-protocol-v2#30]
<img width="556" alt="截屏2020-09-27 上午11 19 42" src="https://user-images.githubusercontent.com/2507027/94372530-58915e80-00b3-11eb-83da-b8415fbea613.png">

而不是显示默认的 yyCrv。

**Comment by Garfield550** [comment]
fixed in 92578f282fddc6abc37bd27ee2fffb0f9105ceb6
