### ISSUE TITLE
当从 Swap 去创建一个从未在 y3dFactory 里有过记录的新 uToken 时会报错

### ISSUE THREAD

**Issue by Garfield550** [carboclan/y3d-protocol-v2#33]
### 复现步骤

1. 部署了新的 y3dFactory 合约地址，旧的 Pair 全部消失，成为初始状态
2. 在 Swap 的 SelectTokenModel 里输入一个未创建过任何 y3d 合约的 uToken 地址，如：[`0x7f76315337E63482043F92A1bD4784290159AD6f`](https://rinkeby.etherscan.io/address/0x7f76315337E63482043F92A1bD4784290159AD6f)
3. 点击 Go to Create y3dToken 按钮会因为 `tokenAInfo` 没有 `tag` 导致使用为 `null` 的 `tokenBInfo.address` 去创建跳转地址 

![image](https://user-images.githubusercontent.com/3471836/94435208-676c3400-01cd-11eb-901c-2fb740b290b3.png)

**Comment by sgxiang** [comment]
修复了
