### ISSUE TITLE
随手换一下 Favicon。

### ISSUE THREAD

**Issue by lychees** [carboclan/y3d-protocol-v2#37]
<img width="140" alt="截屏2020-10-11 下午5 58 31" src="https://user-images.githubusercontent.com/2507027/95695367-6b477f80-0beb-11eb-96a2-3888dde1eb1f.png">

**Comment by xiaotiandada** [comment]
换什么Favicon呢？

**Comment by lychees** [comment]
https://github.com/carboclan/y3d-protocol/blob/master/www/img/favicon.ico
